name: Create Release on Push

on:
  push:
    branches:
      - main  # Change this to your main branch if it's not 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run zip

      - name: Extract package name and version
        id: extract_package_info
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          PACKAGE_VERSION=$(jq -r .version package.json)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME - PACKAGE_VERSION=$PACKAGE_VERSION"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: v${{ env.PACKAGE_VERSION }}
          body: "New release generated by GitHub Actions."
          draft: false
          prerelease: false

      - name: Check for existing release
        id: check_release
        run: |
          RELEASE_NAME="${{ env.PACKAGE_NAME }} v${{ env.PACKAGE_VERSION }}"
          if gh release view "$RELEASE_NAME" >/dev/null 2>&1; then
          echo "Release $RELEASE_NAME already exists."
          exit 0
          else
          echo "Release $RELEASE_NAME does not exist."
          fi

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp_dist.zip
          asset_name: ${{ env.PACKAGE_NAME }}-v${{ env.PACKAGE_VERSION }}.zip
          asset_content_type: application/zip
